// GENERATED by scripts/gen-authz.mjs from specs/design/security.json roles[], in
// DECLARED order — the first is the default persona `?role=` falls back to.
// Do not edit by hand. Re-run `npm run gen` after the design changes.
//
// THE MOCK NEVER WIDENS: each role's grants are exactly what security.json
// declares. A role that cannot reach its own screen is a DESIGN DEFECT to
// report, never a mock to loosen.

export const mockRoles: readonly { readonly name: string; readonly grants: readonly string[] }[] = [
  { name: "Merchant", grants: ["balances:read", "merchants:read", "payment-requests:read", "payment-requests:submit", "payout-accounts:manage", "payouts:read", "payouts:request", "transactions:read", "transactions:refund"] },
  { name: "PlatformAdmin", grants: ["disputes:read-all", "disputes:resolve", "merchants:approve", "merchants:read-all", "merchants:reject", "payouts:read-all", "transactions:read-all"] },
];
