// Generated by `bal openapi --mode service` from ../specs/design/components/payments-api/openapi.yaml,
// then hand-filled: every resource body, the InterceptableService wiring for
// the gateway's signed assertion, and three 201-response wrapper types the
// generator did not add on its own (MerchantCreated, PaymentRequestCreated,
// PayoutCreated) — see code-rules.md: a bare record return maps to 200.

import ballerina/http;
import ballerina/time;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    # Liveness check
    #
    # + return - Service is healthy
    resource function get health() returns http:Ok {
        return http:OK;
    }

    # Register the caller's business as a merchant (pending approval)
    #
    # + return - 201 on success, 400 on invalid input or an existing profile, 401 with no verified caller
    resource function post merchants(http:RequestContext ctx, @http:Payload merchants_body payload)
            returns MerchantCreated|ErrorBadRequest|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        if payload.businessName.trim() == "" || payload.country.trim() == "" || payload.currency.trim() == ""
                || payload.email.trim() == "" {
            return <ErrorBadRequest>{body: {code: 400, message: "businessName, country, currency and email are required"}};
        }
        MerchantRow? existing = check getMerchantByOwner(caller.userId);
        if existing is MerchantRow {
            return <ErrorBadRequest>{body: {code: 400, message: "a merchant profile already exists for this caller"}};
        }
        MerchantRow created = check insertMerchant(caller.userId, payload.businessName, payload.country,
                payload.currency, payload.email);
        return <MerchantCreated>{body: toMerchant(created)};
    }

    # Every merchant, optionally filtered by status
    #
    # + return - Matching merchants
    resource function get merchants("pending"|"approved"|"rejected"|"suspended"? status, int 'limit = 20, int offset = 0)
            returns inline_response_200|error {
        [MerchantRow[], int] result = check listMerchants(status, 'limit, offset);
        Merchant[] items = from MerchantRow r in result[0] select toMerchant(r);
        string basePath = status is string ? string `/merchants?status=${status}` : "/merchants?";
        [string?, string?] links = pageLinks(basePath, 'limit, offset, result[1]);
        return {count: result[1], data: items, next: links[0], previous: links[1]};
    }

    # Approve a pending merchant
    #
    # + return - Merchant approved, or 404 when it does not exist
    resource function post merchants/[string merchantId]/approve() returns MerchantOk|ErrorNotFound|error {
        MerchantRow? updated = check updateMerchantStatus(merchantId, "approved");
        if updated is () {
            return <ErrorNotFound>{body: {code: 404, message: "merchant not found"}};
        }
        notifyMerchantApproval(updated, true);
        return <MerchantOk>{body: toMerchant(updated)};
    }

    # Reject a pending merchant
    #
    # + return - Merchant rejected, or 404 when it does not exist
    resource function post merchants/[string merchantId]/reject() returns MerchantOk|ErrorNotFound|error {
        MerchantRow? updated = check updateMerchantStatus(merchantId, "rejected");
        if updated is () {
            return <ErrorNotFound>{body: {code: 404, message: "merchant not found"}};
        }
        notifyMerchantApproval(updated, false);
        return <MerchantOk>{body: toMerchant(updated)};
    }

    # The caller's own merchant profile
    #
    # + return - The caller's merchant profile, 404 with none, 401 with no verified caller
    resource function get me/merchant(http:RequestContext ctx) returns Merchant|ErrorNotFound|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return <ErrorNotFound>{body: {code: 404, message: "no merchant profile for the caller"}};
        }
        return toMerchant(merchant);
    }

    # The caller's own payout bank account
    #
    # + return - The caller's payout account, 404 with none configured, 401 with no verified caller
    resource function get me/payout\-account(http:RequestContext ctx) returns PayoutAccount|ErrorNotFound|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return <ErrorNotFound>{body: {code: 404, message: "no payout account configured"}};
        }
        PayoutAccountRow? account = check getPayoutAccount(merchant.id);
        if account is () {
            return <ErrorNotFound>{body: {code: 404, message: "no payout account configured"}};
        }
        return toPayoutAccount(account);
    }

    # Create or replace the caller's own payout bank account
    #
    # + return - Payout account saved, 400 with no merchant profile or invalid input, 401 with no verified caller
    resource function put me/payout\-account(http:RequestContext ctx, @http:Payload PayoutAccount payload)
            returns PayoutAccount|ErrorBadRequest|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        if payload.bankName.trim() == "" || payload.accountNumber.trim() == "" || payload.accountHolderName.trim() == "" {
            return <ErrorBadRequest>{body: {code: 400, message: "bankName, accountNumber and accountHolderName are required"}};
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return <ErrorBadRequest>{body: {code: 400, message: "register as a merchant before configuring a payout account"}};
        }
        PayoutAccountRow saved = check upsertPayoutAccount(merchant.id, payload.bankName, payload.accountNumber,
                payload.accountHolderName);
        return toPayoutAccount(saved);
    }

    # Create a payment request for the caller's own business
    #
    # + return - 201 on success, 400 when not an approved merchant or invalid input, 401 with no verified caller
    resource function post me/payment\-requests(http:RequestContext ctx, @http:Payload PaymentRequestInput payload)
            returns PaymentRequestCreated|ErrorBadRequest|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        if payload.amount <= 0d {
            return <ErrorBadRequest>{body: {code: 400, message: "amount must be positive"}};
        }
        if payload.currency.trim() == "" {
            return <ErrorBadRequest>{body: {code: 400, message: "currency is required"}};
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return <ErrorBadRequest>{body: {code: 400, message: "register and get approved as a merchant before creating payment requests"}};
        }
        if merchant.status != "approved" {
            return <ErrorBadRequest>{body: {code: 400, message: "only an approved merchant can create payment requests"}};
        }
        string description = payload?.description ?: "";
        PaymentRequestRow created = check insertPaymentRequest(merchant.id, payload.amount, payload.currency, description);
        return <PaymentRequestCreated>{body: toPaymentRequest(created)};
    }

    # The caller's own payment requests
    #
    # + return - The caller's payment requests, or 401 with no verified caller
    resource function get me/payment\-requests(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns inline_response_200_1|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return {count: 0, data: [], next: (), previous: ()};
        }
        [PaymentRequestRow[], int] result = check listPaymentRequestsByMerchant(merchant.id, 'limit, offset);
        PaymentRequest[] items = from PaymentRequestRow r in result[0] select toPaymentRequest(r);
        [string?, string?] links = pageLinks("/me/payment-requests?", 'limit, offset, result[1]);
        return {count: result[1], data: items, next: links[0], previous: links[1]};
    }

    # A payment request, for the customer paying it
    #
    # + return - The payment request, or 404 when it does not exist
    resource function get payment\-requests/[string requestId]() returns PaymentRequest|ErrorNotFound|error {
        PaymentRequestRow? found = check getPaymentRequestById(requestId);
        if found is () {
            return <ErrorNotFound>{body: {code: 404, message: "payment request not found"}};
        }
        return toPaymentRequest(found);
    }

    # A customer pays a payment request by mobile money or card
    #
    # + return - Payment result, 400 when not payable, 404 when the request does not exist
    resource function post payment\-requests/[string requestId]/pay(@http:Payload PayInput payload)
            returns TransactionOk|ErrorBadRequest|ErrorNotFound|error {
        PaymentRequestRow? paymentRequest = check getPaymentRequestById(requestId);
        if paymentRequest is () {
            return <ErrorNotFound>{body: {code: 404, message: "payment request not found"}};
        }
        if paymentRequest.status != "pending" {
            return <ErrorBadRequest>{body: {code: 400, message: "payment request is not payable"}};
        }
        if payload.customerContact.trim() == "" {
            return <ErrorBadRequest>{body: {code: 400, message: "customerContact is required"}};
        }
        MerchantRow? merchant = check getMerchantById(paymentRequest.merchantId);
        if merchant is () {
            return <ErrorNotFound>{body: {code: 404, message: "payment request not found"}};
        }

        ChargeOutcome outcome = chargeCustomer(merchant.id, paymentRequest.amount, paymentRequest.currency,
                payload.method, requestId);
        time:Utc? paidAt = outcome.status == "succeeded" ? nowUtc() : ();
        TransactionRow txn = check insertTransaction(requestId, payload.method, paymentRequest.amount,
                paymentRequest.currency, outcome.status, payload.customerContact, outcome.gatewayPaymentId, paidAt);

        if outcome.status == "succeeded" {
            check adjustMerchantBalance(merchant.id, paymentRequest.amount);
            check updatePaymentRequestStatus(requestId, "paid");
        }
        if outcome.status == "failed" {
            _ = check insertDispute(txn.id, "system");
        }
        notifyPaymentOutcome(merchant, txn);
        return <TransactionOk>{body: toTransaction(txn)};
    }

    # The caller's own transactions
    #
    # + return - The caller's transactions, or 401 with no verified caller
    resource function get me/transactions(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns inline_response_200_2|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return {count: 0, data: [], next: (), previous: ()};
        }
        [TransactionRow[], int] result = check listTransactionsByMerchant(merchant.id, 'limit, offset);
        Transaction[] items = from TransactionRow r in result[0] select toTransaction(r);
        [string?, string?] links = pageLinks("/me/transactions?", 'limit, offset, result[1]);
        return {count: result[1], data: items, next: links[0], previous: links[1]};
    }

    # Every transaction, across all merchants
    #
    # + return - Matching transactions
    resource function get transactions(int 'limit = 20, int offset = 0) returns inline_response_200_2|error {
        [TransactionRow[], int] result = check listAllTransactions('limit, offset);
        Transaction[] items = from TransactionRow r in result[0] select toTransaction(r);
        [string?, string?] links = pageLinks("/transactions?", 'limit, offset, result[1]);
        return {count: result[1], data: items, next: links[0], previous: links[1]};
    }

    # Refund one of the caller's own completed transactions
    #
    # + return - Refund issued, 400 when not refundable, 404 when not the caller's, 401 with no verified caller
    resource function post me/transactions/[string transactionId]/refund(http:RequestContext ctx, @http:Payload RefundInput payload)
            returns TransactionOk|ErrorBadRequest|ErrorNotFound|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return <ErrorNotFound>{body: {code: 404, message: "transaction not found"}};
        }
        TransactionRow? txn = check getOwnedTransaction(transactionId, merchant.id);
        if txn is () {
            return <ErrorNotFound>{body: {code: 404, message: "transaction not found"}};
        }
        if txn.status != "succeeded" {
            return <ErrorBadRequest>{body: {code: 400, message: "only a succeeded transaction can be refunded"}};
        }
        decimal alreadyRefunded = check getRefundedTotal(transactionId);
        decimal|error resolvedAmount = resolveRefundAmount(payload?.amount, txn.amount, alreadyRefunded);
        if resolvedAmount is error {
            return <ErrorBadRequest>{body: {code: 400, message: "refund amount exceeds the refundable balance"}};
        }
        decimal refundAmount = resolvedAmount;
        _ = check insertRefund(transactionId, refundAmount, payload.reason);
        check adjustMerchantBalance(merchant.id, -refundAmount);
        return <TransactionOk>{body: toTransaction(txn)};
    }

    # The caller's own available balance
    #
    # + return - The caller's balance, or 401 with no verified caller
    resource function get me/balance(http:RequestContext ctx) returns inline_response_200_3|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return {available: 0d, currency: ""};
        }
        return {available: merchant.balance, currency: merchant.currency};
    }

    # Request a payout of the caller's own available balance
    #
    # + return - 201 on success, 400 when over balance or no payout account, 401 with no verified caller
    resource function post me/payouts(http:RequestContext ctx, @http:Payload me_payouts_body payload)
            returns PayoutCreated|ErrorBadRequest|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        if payload.amount <= 0d {
            return <ErrorBadRequest>{body: {code: 400, message: "amount must be positive"}};
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return <ErrorBadRequest>{body: {code: 400, message: "no payout account configured"}};
        }
        PayoutAccountRow? account = check getPayoutAccount(merchant.id);
        if account is () {
            return <ErrorBadRequest>{body: {code: 400, message: "no payout account configured"}};
        }
        if !isPayoutAllowed(payload.amount, merchant.balance) {
            return <ErrorBadRequest>{body: {code: 400, message: "amount exceeds available balance"}};
        }
        PayoutOutcome outcome = requestGatewayPayout(merchant.id, payload.amount, merchant.currency,
                account.bankName, account.accountNumber, newId());
        PayoutRow payout = check insertPayout(merchant.id, payload.amount, outcome.status, outcome.gatewayPayoutId);
        if shouldDebitForPayout(outcome.status) {
            check adjustMerchantBalance(merchant.id, -payload.amount);
        }
        notifyPayoutOutcome(merchant, payout);
        return <PayoutCreated>{body: toPayout(payout)};
    }

    # The caller's own payout history
    #
    # + return - The caller's payouts, or 401 with no verified caller
    resource function get me/payouts(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns inline_response_200_4|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }
        MerchantRow? merchant = check getMerchantByOwner(caller.userId);
        if merchant is () {
            return {count: 0, data: [], next: (), previous: ()};
        }
        [PayoutRow[], int] result = check listPayoutsByMerchant(merchant.id, 'limit, offset);
        Payout[] items = from PayoutRow r in result[0] select toPayout(r);
        [string?, string?] links = pageLinks("/me/payouts?", 'limit, offset, result[1]);
        return {count: result[1], data: items, next: links[0], previous: links[1]};
    }

    # Every payout, across all merchants
    #
    # + return - Matching payouts
    resource function get payouts(int 'limit = 20, int offset = 0) returns inline_response_200_4|error {
        [PayoutRow[], int] result = check listAllPayouts('limit, offset);
        Payout[] items = from PayoutRow r in result[0] select toPayout(r);
        [string?, string?] links = pageLinks("/payouts?", 'limit, offset, result[1]);
        return {count: result[1], data: items, next: links[0], previous: links[1]};
    }

    # Every open or resolved dispute
    #
    # + return - Matching disputes
    resource function get disputes("open"|"resolved"|"rejected"? status, int 'limit = 20, int offset = 0)
            returns inline_response_200_5|error {
        [DisputeRow[], int] result = check listDisputes(status, 'limit, offset);
        Dispute[] items = from DisputeRow r in result[0] select toDispute(r);
        string basePath = status is string ? string `/disputes?status=${status}` : "/disputes?";
        [string?, string?] links = pageLinks(basePath, 'limit, offset, result[1]);
        return {count: result[1], data: items, next: links[0], previous: links[1]};
    }

    # A single dispute
    #
    # + return - The dispute, or 404 when it does not exist
    resource function get disputes/[string disputeId]() returns Dispute|ErrorNotFound|error {
        DisputeRow? dispute = check getDisputeById(disputeId);
        if dispute is () {
            return <ErrorNotFound>{body: {code: 404, message: "dispute not found"}};
        }
        return toDispute(dispute);
    }

    # Resolve or reject a dispute
    #
    # + return - Dispute updated, or 404 when it does not exist
    resource function patch disputes/[string disputeId](@http:Payload DisputeResolution payload)
            returns Dispute|ErrorNotFound|error {
        string notes = payload?.resolutionNotes ?: "";
        DisputeRow? updated = check updateDisputeResolution(disputeId, payload.status, notes);
        if updated is () {
            return <ErrorNotFound>{body: {code: 404, message: "dispute not found"}};
        }
        MerchantRow? merchant = check getMerchantForTransaction(updated.transactionId);
        if merchant is MerchantRow {
            notifyDisputeResolution(merchant, updated);
        }
        return toDispute(updated);
    }
}

public type RefundInput record {
    # defaults to the full transaction amount
    decimal amount?;
    string reason;
};

public type inline_response_200_5 record {
    int count;
    string? next?;
    string? previous?;
    Dispute[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type PaymentRequestInput record {
    decimal amount;
    string currency;
    string description?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type PayoutAccount record {
    string bankName;
    string accountNumber;
    string accountHolderName;
};

public type me_payouts_body record {
    decimal amount;
};

public type DisputeResolution record {
    "resolved"|"rejected" status;
    string resolutionNotes?;
};

public type MerchantOk record {|
    *http:Ok;
    Merchant body;
|};

public type TransactionOk record {|
    *http:Ok;
    Transaction body;
|};

public type MerchantCreated record {|
    *http:Created;
    Merchant body;
|};

public type PaymentRequestCreated record {|
    *http:Created;
    PaymentRequest body;
|};

public type PayoutCreated record {|
    *http:Created;
    Payout body;
|};

public type PayInput record {
    "mobile-money"|"card" method;
    # customer phone number or email for confirmation
    string customerContact;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type Merchant record {
    string id;
    string businessName;
    string country;
    string currency;
    string email?;
    "pending"|"approved"|"rejected"|"suspended" status;
    decimal balance?;
};

public type Transaction record {
    string id;
    string paymentRequestId;
    "mobile-money"|"card" method;
    decimal amount;
    string currency;
    "pending"|"succeeded"|"failed" status;
    string customerContact?;
    string paidAt?;
};

public type PaymentRequest record {
    string id;
    decimal amount;
    string currency;
    string description?;
    "pending"|"paid"|"expired"|"cancelled" status;
    string createdAt?;
};

public type Payout record {
    string id;
    string merchantId?;
    decimal amount;
    "pending"|"completed"|"failed" status;
    string requestedAt?;
};

public type inline_response_200_1 record {
    int count;
    string? next?;
    string? previous?;
    PaymentRequest[] data;
};

public type inline_response_200 record {
    int count;
    string? next?;
    string? previous?;
    Merchant[] data;
};

public type inline_response_200_2 record {
    int count;
    string? next?;
    string? previous?;
    Transaction[] data;
};

public type Dispute record {
    string id;
    string transactionId;
    string raisedBy?;
    "open"|"resolved"|"rejected" status;
    string resolutionNotes?;
    string createdAt?;
};

public type inline_response_200_3 record {
    decimal available;
    string currency;
};

public type inline_response_200_4 record {
    int count;
    string? next?;
    string? previous?;
    Payout[] data;
};

public type merchants_body record {
    string businessName;
    string country;
    string currency;
    string email;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
