// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /disputes"
  | "GET /disputes/{disputeId}"
  | "GET /health"
  | "GET /me/balance"
  | "GET /me/merchant"
  | "GET /me/payment-requests"
  | "GET /me/payout-account"
  | "GET /me/payouts"
  | "GET /me/transactions"
  | "GET /merchants"
  | "GET /payment-requests/{requestId}"
  | "GET /payouts"
  | "GET /transactions"
  | "PATCH /disputes/{disputeId}"
  | "POST /me/payment-requests"
  | "POST /me/payouts"
  | "POST /me/transactions/{transactionId}/refund"
  | "POST /merchants"
  | "POST /merchants/{merchantId}/approve"
  | "POST /merchants/{merchantId}/reject"
  | "POST /payment-requests/{requestId}/pay"
  | "PUT /me/payout-account";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /disputes": { kind: "scope", scope: "disputes:read-all" },
  "GET /disputes/{disputeId}": { kind: "scope", scope: "disputes:read-all" },
  "GET /health": { kind: "public" },
  "GET /me/balance": { kind: "scope", scope: "balances:read" },
  "GET /me/merchant": { kind: "scope", scope: "merchants:read" },
  "GET /me/payment-requests": { kind: "scope", scope: "payment-requests:read" },
  "GET /me/payout-account": { kind: "scope", scope: "payout-accounts:manage" },
  "GET /me/payouts": { kind: "scope", scope: "payouts:read" },
  "GET /me/transactions": { kind: "scope", scope: "transactions:read" },
  "GET /merchants": { kind: "scope", scope: "merchants:read-all" },
  "GET /payment-requests/{requestId}": { kind: "public" },
  "GET /payouts": { kind: "scope", scope: "payouts:read-all" },
  "GET /transactions": { kind: "scope", scope: "transactions:read-all" },
  "PATCH /disputes/{disputeId}": { kind: "scope", scope: "disputes:resolve" },
  "POST /me/payment-requests": { kind: "scope", scope: "payment-requests:submit" },
  "POST /me/payouts": { kind: "scope", scope: "payouts:request" },
  "POST /me/transactions/{transactionId}/refund": { kind: "scope", scope: "transactions:refund" },
  "POST /merchants": { kind: "signedIn" },
  "POST /merchants/{merchantId}/approve": { kind: "scope", scope: "merchants:approve" },
  "POST /merchants/{merchantId}/reject": { kind: "scope", scope: "merchants:reject" },
  "POST /payment-requests/{requestId}/pay": { kind: "public" },
  "PUT /me/payout-account": { kind: "scope", scope: "payout-accounts:manage" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
